### ISSUE TITLE
data error in number of observations

### ISSUE THREAD

**Issue by RLstat** [ellisp/Tcomp-r-package#12]
Hi, I found the package has some data errors in the number of observations. 
I thought the n is suppose to be the number of observation in the time series. However it seems it is different from the length of time series in the training data in many cases. 

To give an example, tourism[[2]]$n = 1979, however length(tourism[[2]]$x) = 163.

**Comment by ellisp** [comment]
Thanks for spotting this.  It was indeed a bug.  Will be corrected in CRAN soon; GitHub version should be right now.
